name: AI-Endo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - pytorch==2.2.1
  - torchvision==0.17.1
  - pytorch-cuda=12.1
  - numpy<2.0
  - pandas
  - scikit-learn
  - scipy
  - setproctitle
  - tensorboard
  - tqdm
  - pip
  - pip:
    - albumentations
    - imageio
    - matplotlib
    - networkx
    - opencv-python-headless
    - pillow
    - scikit-image
    - yacs
    - PyQt5
    - pytorch-metric-learning
